"""Post-hoc integer-pooled work table; does not alter measurement inputs."""
from io_utils import RUN, read, write


def main():
    report = read(RUN / 'results/mechanism-latency.json')
    assert report['status'] == 'qualified'
    keys = ['mma_potential', 'mma_issued', 'mma_omitted_empty_tile',
            'mma_omitted_whole_short_group', 'scalar_products',
            'zero_rows_executed', 'one_nonzero_rows_executed',
            'two_nonzero_rows_executed', 'source_weight_requests_bf16_elements']
    pooled = {}
    for mode in ['t00', 't10', 't01', 't11', 'frozen']:
        sites = report['diagnostics'][mode]['mechanisms_pooled']
        pooled[mode] = {key: sum(sites[site][key] for site in ['h', 'z']) for key in keys}
        row = pooled[mode]
        assert row['mma_potential'] == (row['mma_issued'] + row['mma_omitted_empty_tile']
                                       + row['mma_omitted_whole_short_group'])
    write(RUN / 'results/mechanism-work.json', {
        'coverage': '338 blocks, h and z pooled over all six layers',
        'matrix_unit': 'padded matrix instructions, not canonical logical products',
        'weight_unit': report['diagnostics']['t11']['weight_request_unit'],
        'counts': pooled})
    rows = ['# Pooled h/z work counters', '',
            'All 338 validation blocks and six layers; pool integer counts before dividing.', '',
            '| Mode | Issued matrix instructions | Omitted: empty tiles | Omitted: complete short-row groups | Scalar products |',
            '|---|---:|---:|---:|---:|']
    for mode, row in pooled.items():
        rows.append(f'| {mode} | {row["mma_issued"]:,} | {row["mma_omitted_empty_tile"]:,} | '
                    f'{row["mma_omitted_whole_short_group"]:,} | {row["scalar_products"]:,} |')
    rows += ['', 'The common padded potential is 332,267,520 matrix instructions.',
             'Whole-group completion takes precedence over empty-tile omission; the categories are disjoint.',
             'These are execution counters, not measurements of DRAM traffic, cache misses, or time.',
             'Source: `mechanism-latency.json`; generated by `15_work_summary.py`.']
    (RUN / 'results/mechanism-work.md').write_text('\n'.join(rows) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
