"""Write the evidence bundle, publication tables, and five selected figures."""
import json
from evidence import HERE, DOSES, load_evidence, one
from plots import make_figures


def write_table(name, columns, rows, alignment):
    path = HERE / 'tables' / (name+'.tex')
    path.parent.mkdir(exist_ok=True)
    lines = ['% Generated by Analysis 013/01_build.py; paired eager losses.',
             '\\begin{tabular}{'+alignment+'}', '\\toprule',
             ' & '.join(columns)+r' \\', r'\midrule']
    lines += [' & '.join(row)+r' \\' for row in rows]
    lines += [r'\bottomrule', r'\end{tabular}']
    path.write_text('\n'.join(lines)+'\n', encoding='utf-8')


def tables(d):
    paired = []
    for k in DOSES:
        items = [one(d['contrasts'], parent=p, child=c, dose=k)
                 for p,c in (('A4','A7'),('A4','A4+OL1@4'),('A7','A7+OL1@7'))]
        paired.append([f'{k:g}']+[f"{r['delta_loss']:+.4f} & {r['delta_R_pp']:+.3f}" for r in items])
    write_table('paired-effects', [r'$\kappa$', r'\multicolumn{2}{c}{Add Q/K/V gates}',
                                  r'\multicolumn{2}{c}{Add pressure to A4}',
                                  r'\multicolumn{2}{c}{Add pressure to A7}'], paired, 'rrrrrrr')
    path = HERE/'tables/paired-effects.tex'
    text = path.read_text(encoding='utf-8').replace(r'\midrule',
        r' & $\Delta\mathcal{L}$ & $\Delta R$ (pp) & $\Delta\mathcal{L}$ & $\Delta R$ (pp) & $\Delta\mathcal{L}$ & $\Delta R$ (pp) \\'+'\n'+r'\midrule',1)
    path.write_text(text,encoding='utf-8')
    differences = [[f"{r['dose']:g}", f"{r['delta_loss']:+.4f}", f"{r['delta_R_pp']:+.3f}"]
                   for r in d['pressure_response_differences']]
    write_table('pressure-differences', [r'$\kappa$', r'$D_{\mathcal L}$', r'$D_R$ (pp)'], differences, 'rrr')
    for scale in ('14M', '70M', '410M'):
        rows = [r for r in d['trained'] if r['scale'] == scale]
        write_table('trained-'+scale, ['Intervention', 'Dose', 'Loss', r'$\Rmodel$ (\%)'],
                    [[r'\texttt{'+r['family']+'}', '--' if r['dose'] is None else f"{r['dose']:g}",
                      f"{r['loss']:.6f}", f"{100*r['R_model']:.4f}"] for r in rows], 'lrrr')
    for scale in ('14M', '70M', '410M'):
        rows = []
        for p in [i/10 for i in range(10)]:
            a = one(d['clipping'], scale=scale, family='A0 clipped', dose=p)
            b = one(d['clipping'], scale=scale, family='A1-H clipped', dose=p)
            rows.append([f'{p:.1f}', f"{a['loss']:.6f}", f"{100*a['R_model']:.4f}",
                         f"{b['loss']:.6f}", f"{100*b['R_model']:.4f}"])
        write_table('clipping-'+scale, ['$p$', 'A0 loss', r'A0 $\Rmodel$ (\%)',
                                      'ReLU loss', r'ReLU $\Rmodel$ (\%)'], rows, 'rrrrr')
    names = {'a0-gelu':'A0','a1h-relu':'A1-H','a4-ol1-kappa-0':'A4+OL1@4, 0',
             'a4-ol1-kappa-0p5':'A4+OL1@4, .5','a7-ol1-kappa-0':'A7+OL1@7, 0',
             'a7-ol1-kappa-0p5':'A7+OL1@7, .5'}
    write_table('runtime', ['Condition', r'$\Rmodel$ (\%)', r'$R_{\rm covered}$ (\%)', 'Batch 1', 'Batch 32'],
                [[names[r['condition_id']], f"{100*r['R_model']:.2f}", f"{100*r['R_covered_linear']:.2f}",
                  f"{r['b1_paired_speedup']:.3f}$\\times$", f"{r['b32_paired_speedup']:.3f}$\\times$"] for r in d['runtime']], 'lrrrr')
    architecture = []
    for scale in ('14M','70M','410M'):
        r=one(d['trained'],scale=scale,family='A7+OL1@7',dose=.5)
        c=r['counts']; ex=one(d['exposure'],scale=scale)
        architecture.append([scale, f"{ex['parameters']/1e6:.1f}M", f"{ex['tokens_per_parameter']:.1f}",
                             f"{100*c['block_product_count']/c['model_product_count']:.2f}",
                             f"{100*r['R_block']:.2f}",f"{100*r['R_model']:.2f}"])
    write_table('architecture', ['Model','Parameters','Tok./param.',r'Block share (\%)',r'$\Rblock$ (\%)',r'$\Rmodel$ (\%)'],architecture,'lrrrrr')
    screen = d['lr_screen']
    write_table('lr-screen', ['Peak learning rate', 'Late training loss', 'Validation loss', 'Selected'],
                [[f"{r['peak_learning_rate']:.0e}", f"{r['selection_metric']:.6f}",
                  f"{r['validation_loss_not_used_for_selection']:.6f}",
                  'yes' if r['condition_id'] == screen['selected_condition_id'] else '']
                 for r in screen['arms']], 'lrrl')
    budget_rows=[]
    d['loss_budget_comparisons']=[]
    for budget in (.05,.1,.25,.5,1.0):
        cells=[f'{budget:.2f}']
        for scale in ('14M','70M'):
            base=one(d['clipping'],scale=scale,family='A0 clipped',dose=0.)['loss']
            for kind in ('trained','clipping'):
                eligible=[r for r in d[kind] if r['scale']==scale and r['loss']<=base+budget]
                best=max(eligible,key=lambda r:r['R_model'])
                cells.append(f"{100*best['R_model']:.2f}")
                d['loss_budget_comparisons'].append({'scale':scale,'budget':budget,'kind':kind,'selected':best})
        budget_rows.append(cells)
    write_table('loss-budgets',[r'Loss allowance',r'14M trained',r'14M clipped',r'70M trained',r'70M clipped'],budget_rows,'rrrrr')
    # Human-readable complete numeric bundle independent of TeX rendering.
    lines=['# Complete evidence table', '', 'Loss and R_model use the same eager pass.', '',
           '| Scale | Family | Dose | Loss | R_model (%) |', '|---|---|---:|---:|---:|']
    lines += [f"| {r['scale']} | {r['family']} | {r['dose']} | {r['loss']:.6f} | {100*r['R_model']:.4f} |" for r in d['trained']+d['clipping']]
    (HERE/'tables.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')


def main():
    d=load_evidence()
    tables(d)
    (HERE/'figure_data.json').write_text(json.dumps(d,indent=2,sort_keys=True)+'\n',encoding='utf-8')
    make_figures(d)
    print(f"Built {len(d['trained'])} trained rows, {len(d['clipping'])} clipping rows, 6 runtime rows and 5 PDFs.")


if __name__ == '__main__':
    main()
