"""Export two retained 14M endpoints; no inference or new timing measurements."""
import hashlib
import importlib.util
import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SOURCE = HERE / 'data/operation-bypass.json'
spec = importlib.util.spec_from_file_location('bypass', HERE / '18_reduce_operation_bypass.py')
bypass = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bypass)


def main():
    data = json.loads(SOURCE.read_text(encoding='utf-8'))
    selected = []
    for condition in ['c35', 'c30']:
        rows = [r for r in data['settings'] if r['setting_id'] == f'trained-14M-{condition}']
        assert len(rows) == 1
        row = rows[0]
        assert row['model'] == '14M' and row['kappa'] == 0.5 and row['kernel'] == 'K050'
        diagnostic = bypass.read(ROOT / row['diagnostic_source'])
        assert diagnostic['coverage'] == {
            'blocks': 338, 'documents': 500, 'input_tokens': 692224, 'excluded_tail_tokens': 1444}
        canonical = {'per_operation': {
            key: {'product_count': op['logical_products'], 'zero_product_count': op['fp16_zero_products']}
            for key, op in row['operations'].items()}}
        rebuilt = bypass.operations(diagnostic, canonical)
        assert all(value == row['operations'][key][field]
                   for key, op in rebuilt.items() for field, value in op.items())
        for op in row['operations'].values():
            assert op['potential_mmas'] == op['issued_mmas'] + op['bypassed_mmas']
            assert op['bypass_fraction'] == op['bypassed_mmas'] / op['potential_mmas']
        for mode, candidate in [('all_off', 'k050-no-skip'),
                                ('projection_only', 'k050-attention-dense'), ('full', 'k050')]:
            measured = bypass.graph_means(condition, candidate, row['weight_sha256'])
            retained = row['skip_ablation']['graph_means_ms'][mode]
            assert all(math.isclose(measured[k], retained[k], rel_tol=1e-12) for k in measured)
        selected.append(row)

    lines = [r'% Generated by Analysis024/24_build_kernel_mechanism_table.py.',
             r'\begin{tabular}{@{}lrr@{}}', r'\toprule',
             r' & $T_4/P_h$ & $T_7/P_{\mathrm{all}}$ \\', r'\midrule',
             r'\multicolumn{3}{@{}l}{\textit{Matrix instructions bypassed (\%)}} \\']
    for op, label in [('qkv_projection', r'$a$: QKV projection'),
                      ('mlp_w1', r'$m$: FFN-up'), ('mlp_w2', r'$h$: FFN-down'),
                      ('attention_output_projection', r'$z$: attention-output projection'),
                      ('qk_scores', r'$q,k$: $QK$ scores'),
                      ('probability_value', r'$v$: $PV$ product')]:
        values = [100 * r['operations'][op]['bypass_fraction'] for r in selected]
        lines.append(label + ' & ' + ' & '.join(f'{v:.1f}' for v in values) + r' \\')
    lines.extend([r'\midrule', r'\multicolumn{3}{@{}l}{\textit{Full-model latency (ms)}} \\'])
    for mode, label in [('all_off', 'All skipping off'),
                        ('projection_only', 'Projection skipping only'),
                        ('full', 'Projection + attention skipping')]:
        values = [r['skip_ablation']['graph_means_ms'][mode]['candidate_graph'] for r in selected]
        lines.append(label + ' & ' + ' & '.join(f'{v:.3f}' for v in values) + r' \\')
    lines.extend([r'\bottomrule', r'\end{tabular}', ''])
    tex = '\n'.join(lines)
    (HERE / 'data/kernel-mechanisms.tex').write_text(tex, encoding='utf-8', newline='\n')
    (ROOT / 'manuscript/draft/tables/kernel-mechanisms.tex').write_text(tex, encoding='utf-8', newline='\n')
    hashes = bypass.SOURCES | {
        SOURCE.relative_to(ROOT).as_posix(): hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
        Path(__file__).relative_to(ROOT).as_posix(): hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        (HERE / '18_reduce_operation_bypass.py').relative_to(ROOT).as_posix():
            hashlib.sha256((HERE / '18_reduce_operation_bypass.py').read_bytes()).hexdigest()}
    export = {'scope': 'Retained 14M kappa=0.5 measurements; no individual-site timing attribution',
              'coverage': {'checkpoints': 2, 'validation_blocks_per_checkpoint': 338,
                           'documents': 500, 'input_tokens': 692224, 'excluded_tail_tokens': 1444,
                           'timing_inputs': 64, 'timing_passes': 7, 'process_replicates': 3},
              'checkpoints': selected, 'source_sha256': hashes,
              'verification': 'Six mode/checkpoint means rebuilt from 8064 raw candidate timing samples; '
                              'native paired timings also verified; 12 integer-count bypass ratios verified.'}
    (HERE / 'data/kernel-mechanisms.json').write_text(
        json.dumps(export, indent=2) + '\n', encoding='utf-8', newline='\n')
    print('Verified 12 bypass ratios and 6 latency means; wrote analysis export and manuscript table.')


if __name__ == '__main__':
    main()
