"""Export the verified Run037 conditional effects; no new GPU measurements."""
import hashlib
import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
RUN = ROOT / 'runs/037-2026-09-19-pythia14m-operation-latency'


def main():
    source = RUN / 'results/operation-latency.json'
    audit_path = RUN / 'results/conditional-effects-audit.json'
    report = json.loads(source.read_text(encoding='utf-8'))
    audit = json.loads(audit_path.read_text(encoding='utf-8'))
    assert audit['source_sha256'] == hashlib.sha256(source.read_bytes()).hexdigest()
    assert report['status'] == 'qualified'
    assert audit['qualified_processes'] == 30
    assert audit['raw_timing_samples_verified'] == 26880
    assert audit['maximum_absolute_logit_error'] == 0.0
    assert [r['operation'] for r in audit['rows']] == ['a', 'm', 'h', 'z', 'qk', 'pv']
    labels = [r'$a$: QKV projection', r'$m$: FFN-up', r'$h$: FFN-down',
              r'$z$: attention-output projection', r'$q,k$: $QK$ scores',
              r'$v$: $PV$ product']
    lines = [r'% Generated by Analysis024/25_build_operation_latency_table.py.',
             r'\begin{tabular}{@{}lrrr@{}}', r'\toprule',
             r'Operation & Bypass (\%) & Saved time ($\mu$s) & Process span ($\mu$s) \\',
             r'\midrule']
    for row, label in zip(audit['rows'], labels):
        mode = 'without-' + row['operation']
        value = 1000 * (report['latencies_ms'][mode] - report['latencies_ms']['full'])
        assert math.isclose(value, row['saved_microseconds'], abs_tol=1e-10)
        percent = 100 * row['bypassed'] / (row['issued'] + row['bypassed'])
        assert math.isclose(percent, row['bypass_percent'], abs_tol=1e-10)
        low, high = report['process_ranges_ms'][mode]
        full_low, full_high = report['process_ranges_ms']['full']
        span = [1000 * (low - full_high), 1000 * (high - full_low)]
        assert all(math.isclose(x, y, abs_tol=1e-10) for x, y in
                   zip(span, row['cross_process_difference_span_us']))
        lines.append(f'{label} & {percent:.1f} & ${value:+.1f}$ & '
                     f'$[{span[0]:+.1f}, {span[1]:+.1f}]$' + r' \\')
    lines.extend([r'\bottomrule', r'\end{tabular}', ''])
    tex = '\n'.join(lines)
    (HERE / 'data/operation-latency.tex').write_text(tex, encoding='utf-8', newline='\n')
    (ROOT / 'manuscript/draft/tables/operation-latency.tex').write_text(
        tex, encoding='utf-8', newline='\n')
    sources = [source, audit_path, RUN / '12_report.py', Path(__file__).resolve()]
    export = {
        'scope': 'Run037: 14M T7/Pall, kappa=0.5; conditional, non-additive latency effects',
        'source_sha256': {p.relative_to(ROOT).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
                          for p in sources},
        'coverage': report['diagnostics']['full']['coverage'],
        'timing': {'inputs': 64, 'passes': 7, 'processes_per_mode': 3},
        'controls_ms': {k: report['latencies_ms'][k] for k in ['frozen', 'full', 'off', 'projection']},
        'control_process_ranges_ms': {k: report['process_ranges_ms'][k]
                                     for k in ['frozen', 'full', 'off', 'projection']},
        'attention_overhead_microseconds': 1000 * (report['latencies_ms']['full'] -
                                                 report['latencies_ms']['projection']),
        'verification': {k: audit[k] for k in ['raw_timing_samples_verified', 'qualified_processes',
                                              'maximum_absolute_logit_error', 'interpretation']},
        'rows': audit['rows'],
    }
    (HERE / 'data/operation-latency.json').write_text(
        json.dumps(export, indent=2) + '\n', encoding='utf-8', newline='\n')
    print('Verified six bypass ratios, conditional effects and process spans; exported manuscript table.')


if __name__ == '__main__':
    main()
