"""Compact paired appendix results from retained checkpoints; no new measurements."""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SOURCE = ROOT / 'analyses/030-2026-09-20-70m-t2-optimized-endpoint/data/full-trained-results.json'
assert hashlib.sha256(SOURCE.read_bytes()).hexdigest() == 'eaf1d4d8bdf8c86fa4231c81cec7cc498f20d21f1b2c948ba95352c587925752'
data = json.loads(SOURCE.read_text())['trained_points']
refs = json.loads((HERE / 'data/combined-figure.json').read_text())['base_references']
bases = {r['model']: r for r in refs if r['backend'] == 'PyTorch'}
groups = [('0', 'none'), ('1', 'none'), ('hz', 'h'), ('4', 'h'), ('4', 'all'), ('7', 'h'), ('7', 'all')]
lines = [r'% Generated by Analysis034/03_appendix_table.py; observations/004-lean-appendix.md.',
         r'\begin{table}[!htbp]', r'\centering\footnotesize', r'\setlength{\tabcolsep}{2pt}',
         r'\renewcommand{\arraystretch}{1.12}',
         r'\caption{\textbf{14M/70M results.} Parentheses give changes in loss and latency relative to each size\textquotesingle s $T_0/P_0$ Base. Base uses dense PyTorch/SDPA; other rows use the optimized implementation for their size. Deltas use the fixed Base references shown, with negative values indicating reductions. Latency is in ms (RTX\,5090, BF16, batch one, 2,048 tokens, full logits). OL1 uses $\lambda=b=1$.}',
         r'\label{tab:endpoints-14m-70m}',r'\begin{tabular}{@{}llrrrrrr@{}}',r'\toprule',
         r'\multirow{2}{*}{Recipe} & \multirow{2}{*}{$\kappa$} & \multicolumn{3}{c}{14M} & \multicolumn{3}{c}{70M} \\',
         r'\cmidrule(lr){3-5}\cmidrule(l){6-8}',
         r' & & $\Smodel$ (\%) & Loss ($\Delta$) & Latency ($\Delta$) & $\Smodel$ (\%) & Loss ($\Delta$) & Latency ($\Delta$) \\',r'\midrule']
records=[]
for group_index,(scope,pressure) in enumerate(groups):
    kappas = [None] if scope in ['0','1'] else [0,.01,.05,.1,.5]
    label = {'0':r'$T_0/P_0$ (Base)', '1':r'$T_1/P_0$ (ReLU)'}.get(scope)
    if label is None:
        label = '$T_'+('2' if scope=='hz' else scope)+'/P_{'+('h' if pressure=='h' else r'\mathrm{all}')+'}$'
    for i,kappa in enumerate(kappas):
        row_label = label if len(kappas)==1 else (r'\multirow{5}{*}{'+label+'}' if i==0 else '')
        cells=[row_label, '---' if kappa is None else f'{kappa:g}']
        for size in ['14M','70M']:
            matches=[r for r in data if (r['model'],r['scope'],r['pressure'],r['kappa'])==(size,scope,pressure,kappa)]
            assert len(matches)==1
            r=matches[0]; base=bases[size]
            latency=base['latency_ms'] if scope=='0' else r['latency_ms']
            assert r['coverage']['sequences']==338
            if size=='70M' and scope!='0':
                assert r['qualified']['candidate_graph'] and latency==r['implementation_latency_ms']['candidate_graph']
            dl=r['loss']-base['loss']; dt=latency-base['latency_ms']
            cells += [f"{r['sparsity']:.2f}",f"{r['loss']:.2f} ({dl:+.3f})",f"{latency:.2f} ({dt:+.3f})"]
            records.append(dict(model=size,scope=scope,pressure=pressure,kappa=kappa,
                                checkpoint_key=r['checkpoint_key'],loss=r['loss'],sparsity=r['sparsity'],
                                latency_ms=latency,delta_loss=dl,delta_latency_ms=dt,
                                timing_session=r['timing_session']))
        lines.append(' & '.join(cells)+r' \\')
    if group_index<len(groups)-1: lines.append(r'\midrule')
lines += [r'\bottomrule',r'\end{tabular}',r'\end{table}','']
assert len(records)==54
tex='\n'.join(lines)
(ROOT/'manuscript/draft/tables/compact-results/14m-70m.tex').write_bytes(tex.encode())
(HERE/'data/appendix-paired-results.json').write_text(json.dumps(dict(source=str(SOURCE.relative_to(ROOT)),
    source_sha256=hashlib.sha256(SOURCE.read_bytes()).hexdigest(),base_references=bases,rows=records),indent=2)+'\n')
print('Exported 27 paired rows with optimized latency and fixed native-Base deltas.')
